version: '3'

services:
  nginx:
    # image: nginx:latest
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "9999:9999"
    volumes:
      - ./requirements/nginx/config:/etc/nginx/conf.d/
      - ./requirements/nginx/pong:/var/www/pong
    depends_on:
      - postgresql
    restart: always
    networks:
      - my_network
    init: true

  postgresql:
    image: postgres:latest
    build:
      context: .
      dockerfile: ./requirements/postgresql/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pong
      POSTGRES_PASSWORD: ping
      POSTGRES_DB: pong_database
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      # - ./requirements/postgresql/database/pong.sql:/docker-entrypoint-initdb.d/pong.sql
    restart: always
    networks:
      - my_network
    init: true

networks:
  my_network: {}
    # driver: bridge

volumes:
  postgresql_data:
