version: '3.8'

services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    # command: 
    #   - "gunicorn pong.wsgi:application --bind 0.0.0.0:8000 &"
    #   - "daphne pong.asgi:application -b 0.0.0.0 -p 8001 &"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
      - 8001
    env_file:
      - ./.env
    depends_on:
      - db
    develop:
      watch:
        - path: ./app/
          target: /home/app/web/
          action: sync+restart
          delay: 30


  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6378:6379
   


  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 9999:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    restart: always
    init: true  

volumes:
  postgres_data:
  static_volume:
