version: '3.8'

services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn pong.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    develop:
      watch:
        - path: ./app/
          target: /home/app/web/
          action: sync+restart

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 9999:80
    depends_on:
      - web

  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090 #should be not accessible for users
    volumes:
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000 #should be not accessible for users
    volumes:
      - grafana-data:/var/lib/grafana


volumes:
  postgres_data:
  static_volume:
  prometheus-data:
  grafana-data:

