version: '3.8'

services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command:   gunicorn pong.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      # - daphne
    develop:
      watch:
        - path: ./app/
          target: /home/app/web/
          action: sync+restart
          delay: 30

  daphne:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: daphne pong.asgi:application -b 0.0.0.0 -p 8001
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8001
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #   ports:
  #     - 9999:80
  #   depends_on:
  #     - web

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 9999:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    restart: always
    init: true  

volumes:
  postgres_data:
  static_volume:
