global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
    - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'node'
    static_configs:
      - targets: ['prometheus-node-exporter:9100']