global:
  scrape_interval: 1m
  evaluation_interval: 1m

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093 

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    tls_config:
      ca_file: 'rootCA.pem'
    basic_auth:
      username: admin
      password: password
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'nginx'
    static_configs:
    - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'node'
    static_configs:
      - targets: ['prometheus-node-exporter:9100']