name: Docker Build Test

on:
  push:
    branches:
      - mariia
  pull_request:
    branches:
      - mariia

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build and Run Containers
        run: make all

      - name: Check Docker Containers Status
        run: |
          docker ps -a
          exit $(docker ps -aq -f status=exited | wc -l)
