name: Docker Build Test

on:
  push:

#job on building container and testing whether we can reach end points
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove containerd.io -y
          sudo apt-get update

      - name: Install Docker
        run: |
          sudo apt-get install -y docker.io

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Build and Run Containers
        run: make all

      - name: Check Docker Containers Status
        run: |
          docker ps -a
          exit $(docker ps -aq -f status=exited | wc -l)
      
      - name: Elastic search Reachability
        run: |
          response=$(curl -w "%{http_code}\n" -X GET 'http://localhost:9200')
          if [ $response -eq 60 ]; then
            echo "elasticsearch is reachable and require certificate"
          else
            echo "elasticsearch not reachable"
            exit 1
          fi